import "./js/header";
import "./js/localization";
import "./js/faq";
import "./js/services-swiper";
import "./js/reviews-swiper";
import "./js/form";
import "./js/modal";
import "./js/team-modal";
import "./js/footer";
